twitter: &twitter
  twitter_api_key: <%= ENV["YOUR_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["YOUR_CONSUMER_SECRET"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter